version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: users_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - user_service_network

  user_service:
    build: .
    container_name: user_service
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - DATABASE_NAME=users_db
    depends_on:
      - mongodb
    networks:
      - user_service_network
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  user_service_network:
    driver: bridge

volumes:
  mongodb_data:
